# Generated by Django 4.2b1 on 2023-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergens',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('kilocalories', models.PositiveIntegerField(default=0, verbose_name='Kilocalories')),
                ('proteins', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Proteins')),
                ('fats', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Fats')),
                ('carb', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Carbohydrates')),
                ('allergens', models.ManyToManyField(to='app.allergen', verbose_name='Allergen list')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
