# Generated by Django 4.2 on 2023-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menu_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='kalo_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
