version: "3.9"

services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:13-alpine3.18
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres

  web:
    container_name: web
    image: ${IMAGE_NAME}
    build: ./src
    ports:
      - "${PORT}:${PORT}"
    command: python3 ./src/manage.py runserver 0.0.0.0:${PORT}
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge
