version: "3.9"

services:
  db:
    container_name: pg_db
    image: postgres:13.3
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  web:
    container_name: web
    image: ${IMAGE_NAME}
    build: ./src
    volumes:
      - db_data:/opt/file
    ports:
      - "${PORT}:${PORT}"
    command: python ./src/manage.py runserver 0.0.0.0:8090

volumes:
  db_data: