version: "3.9"

services:
  web:
    container_name: web
    image: ${IMAGE_NAME}
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "8090:8090"
    command: python ./src/manage.py runserver 0.0.0.0:8090
